# Generated by Django 5.2.7 on 2026-01-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
