# Generated by Django 6.0 on 2026-01-06 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('parent_phone', models.CharField(help_text='Primary contact number', max_length=15)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Cached running balance. Positive means debt, Negative means credit.', max_digits=10)),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.studentclass')),
                ('user', models.OneToOneField(blank=True, help_text='Link to a system user account for portal access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
