# Generated by Django 6.0 on 2026-01-06 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2024/2025', max_length=20, unique=True)),
                ('is_current', models.BooleanField(default=False, help_text='Set to True if this is the current active session')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Grade 1', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Student Classes',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Term 1, Term 2', max_length=20)),
                ('is_current', models.BooleanField(default=False, help_text='Set to True if this is the current active term')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.academicsession')),
            ],
            options={
                'unique_together': {('session', 'name')},
            },
        ),
    ]
