# Generated by Django 5.2.7 on 2026-01-13 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exported Data'), ('PAYMENT', 'Recorded Payment'), ('OTHER', 'Other')], max_length=20)),
                ('target_model', models.CharField(help_text='Model name e.g. Student, Transaction', max_length=100)),
                ('target_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('target_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=255, null=True)),
                ('details', models.TextField(blank=True, help_text='Additional context', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
